config/routes.rb
Showtime::Application.routes.draw do
  resources :movies do
    get :download, :on => :collection
  end
  resources :genres
  resources :reviews

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews

  def showtime
    "#{formatted_date} #{formatted_time}"
#    "#{formatted_date} (#{formatted_time})"
  end

  def formatted_date
    showtime_date.strftime("%Y-%m-%d")
  end

  def formatted_time
    #format_string = showtime_time.min.zero? ? "%l%p" : "%l:%M%p"
    puts showtime_time
    showtime_time.strftime("%H:%M")
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    #@genres = Genre.all
    @genres = Genre.page(1)
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @genre }
    end
  end

  def show
    @genre = Genre.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @genre }
    end
  end

  def new
    @genre = Genre.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @genre }
    end
  end

  def create
    @genre= Genre.new(:name => params[:name])
    respond_to do |format|
      if @genre.save
        format.html { redirect_to(movies_path) }
        format.xml  { head :ok }
      else
        format.html { redirect_to(movies_path) }
        format.xml  { head :ok }
      end
    end
  end
end

app/controllers/movies_controller.rb
# coding: utf-8

require 'thinreports'

class MoviesController < ApplicationController

  def index
    @genres = Genre.all
    @movies = Movie.order("title").page(params[:page]).per(5)
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @movie }
    end
  end

  def download
    report = ThinReports::Report.new :layout => File.join(Rails.root, 'reports', 'foo.tlf')
    report.start_new_page
    @mvs = Movie.all
    @mvs.each do |mv|
      report.page.list(:mv_list) do |list|
        list.add_row :title => mv.title, :showtime => mv.showtime
      end
    end
    filename = "foo.pdf"
    #report.generate_file("public/docs/#{filename}")
    #send_file("public/docs/#{filename}")
    send_data report.generate, :filename => "thinreports.pdf", :type => 'application/pdf'
  end

  def show
    @movie = Movie.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @movie }
    end
  end

  def new
    @genres = Genre.all
    @movie = Movie.new

    @show_year_list = Array.new(['2012', '2013'])

    @show_month_list = Array.new
    (1..12).each do |month|
      @show_month_list.push(sprintf("%02d", month))
    end

    @show_day_list = Array.new
    (1..31).each do |day|
      @show_day_list.push(sprintf("%02d", day))
    end

    @show_hour_list = Array.new
    (0..23).each do |hour|
      @show_hour_list.push(hour.to_s)
    end

    @show_min_list = Array.new(['00', '30'])

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @movie }
    end
  end

  def create
    @movie= Movie.new(
      :title => params[:title], 
      :genre_id => params[:genre_id],
      :showtime_date => params[:show_year] + "-" + 
                        params[:show_month] + "-" + 
                        params[:show_day],
      :showtime_time => params[:show_hour] + ":" + 
                        params[:show_min]
    )
    respond_to do |format|
      if @movie.save
        format.html { redirect_to(movies_path) }
        format.xml  { head :ok }
      else
        format.html { redirect_to(movies_path) }
        format.xml  { head :ok }
      end
    end
  end
=begin
=end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @movies = Movie.all
    @reviews = Review.all
    @reviews.each do |review|
      puts review.movie.title + ':' + review.subject
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @reviews }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/genres/index.html.erb
<% @genres.each do |genre| %>
  <%= link_to genre.name, genre_path(genre.id)  %><br/>
<% end %>

app/views/genres/new.html.erb
<form accept-charset="UTF-8" action="/genres" method="post">
Welcome to New Genre
<br/>

<input type='text' name='name' />
<input type='submit' value='Save' />

</form>

app/views/genres/show.html.erb
<%= @genre.movies.count %> movie
<table border="1">
  <tr>
    <th>Title</th>
    <th>Release Year</th>
    <th>Show Time</th>
  </tr>
<% @genre.movies.each do |movie|  %>
  <tr>
    <td><%= movie.title %></td>
    <td>1980</td>
    <td><%= movie.showtime %></td>
  </tr>
<% end  %>
</table>
<%= link_to 'Top', movies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Showtime</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
Welcome to Top Page!
<br/>
<br/>　

<%= link_to 'Add Movie', new_movie_path %>　
<%= link_to 'Add Genre', new_genre_path %><br/>

<br/>
Genres
<br/>
<br/>　
<% @genres.each do |genre| %>
  <%= link_to genre.name, genre_path(genre.id) %>　
<% end %>
<br/>
<br/>
<% @movies.each do |movie| %>
　<%= movie.title %><br/>
<% end %>
<br/>
<%= paginate @movies %>
<br/>
<%= link_to "Download Movie List", download_movies_path %><br/>
<br/>
<%= link_to 'Review', reviews_path %><br/>

app/views/movies/new.html.erb
<form accept-charset="UTF-8" action="/movies" method="post">
<h1>Add Movie</h1>
<dl>
  <dt>
    <label for="movie_title">Title</label>
  </dt>
  <dd><br/>
    <input type="text" name="title" id="movie_title" />
  </dd>
</dl>
<dl>
  <dt>
    <label for="movie_release_year">Release Year</label>
  </dt>
  <dd><br/>
    <select name="release" id="movie_release_year">
      <option value="1980">1980</option>
      <option value="1981">1981</option>
      <option value="1982">1982</option>
    </select>
  </dd>
</dl>
<dl>
  <dt>
    <label>Genre</label>
  </dt>
  <dd><br/>
    <% @genres.each do |genre| %>
      <input type="radio" name="genre_id" id="<%= genre.name %>" value="<%= genre.id %>"><%= genre.name %></input>
    <% end %>
  </dd>
</dl>

<dl>
  <dt>
    <label>Show Date</label>
  </dt>
  <dd><br/>
    <select name="show_year" id="movie_show_year">
      <% @show_year_list.each do |year| %>
        <option value="<%= year %>"><%= year %></option>
      <% end %>
    </select>年　
    <select name="show_month" id="movie_show_month">
      <% @show_month_list.each do |month| %>
        <option value="<%= month %>"><%= month %></option>
      <% end %>
    </select>月　
    <select name="show_day" id="movie_show_day">
      <% @show_day_list.each do |day| %>
        <option value="<%= day%>"><%= day %></option>
      <% end %>
    </select>日
  </dd>
</dl>

<dl>
  <dt>
    <label>Show Time</label>
  </dt>
  <dd><br/>
    <select name="show_hour" id="movie_show_hour">
      <% @show_hour_list.each do |hour| %>
        <option value="<%= hour %>"><%= hour %></option>
      <% end %>
    </select>時　
    <select name="show_min" id="movie_show_min">
      <% @show_min_list.each do |min| %>
        <option value="<%= min %>"><%= min %></option>
      <% end %>
    </select>分
  </dd>
</dl>
<input type="submit" name="save" id="movie_save" value="Save" />
</form>

app/views/reviews/index.html.erb
<h1>Review List</h1>
<%= @reviews.count %> reviews
<br/>
<%= link_to 'Add review', new_review_path %><br/>
<br/>


<table border="1">
  <tr>
    <th>Movie title</th>
    <th>Subject</th>
    <th>Detail</th>
  </tr>
<% @reviews.each do |review| %>
  <tr>
    <td><%= review.movie.title %></td>
    <td><%= review.subject %></td>
    <td><%= review.detail %></td>
  </tr>
<% end %>
</table>

<br/>
Fix from windows.
<br/>

<%= link_to 'Top', movies_path %>
